// Precomputed Pinyin initials mapping for all 70 students in 2026 CS II
const STUDENT_PINYIN_MAP: Record<string, string> = {
  "曹知远": "czy",
  "陈思翰": "csh",
  "齐济": "qj",
  "刘润霖": "lrl",
  "王浩嘉": "whj",
  "陈秋旭": "cqx",
  "郑翔兮": "zxx",
  "张京鹏": "zjp",
  "王艺霖": "wyl",
  "宋哈霓": "shn",
  "杨留俊": "ylj",
  "葛懿德": "gyd",
  "刘柏智": "lbz",
  "零爽": "ls",
  "张金榜": "zjb",
  "孙善斌": "ssb",
  "林子豪": "lzh",
  "谢欣桐": "xxt",
  "韩啸": "hx",
  "杜镇宇": "dzy",
  "谢一鸣": "xym",
  "颜辰哲": "ycz",
  "陈锡平": "cxp",
  "叶楚楚": "ycc",
  "章之圆": "zzy",
  "鲁杨琦": "lyq",
  "李佳庆": "ljq",
  "王若辰": "wrc",
  "付云枫": "fyf",
  "汝以恒": "ryh",
  "苗沛青": "mpq",
  "张铧仁": "zhr",
  "梁鸿翔": "lhx",
  "张子皓": "zzh",
  "帅竣雯": "sjw",
  "杨雨桐": "yyt",
  "邓翔尹": "dxy",
  "龙嘉凯": "ljk",
  "何承骏": "hcj",
  "朱祺睿": "zqr",
  "梁子涵": "lzh",
  "张宇辰": "zyc",
  "林易": "ly",
  "冯瀚霖": "fhl",
  "韩承轩": "hcx",
  "隋阳": "sy",
  "王梓钰": "wzy",
  "叶锦畅": "yjc",
  "曹灵": "cl",
  "余乐妍": "yly",
  "龙官震": "lgz",
  "李雨晨": "lyc",
  "李梓源": "lzy",
  "吴慧仁": "whr",
  "肖燃": "xr",
  "邹楚宁": "zcn",
  "王俊博": "wjb",
  "符浩": "fh",
  "刘正一": "lzy",
  "陈孜堂": "czt",
  "杨舜尧": "ysy",
  "陶晓鹏": "txp",
  "郭永强": "gyq",
  "李海聪": "lhc",
  "朱怡光": "zyg",
  "郭浩川": "ghc",
  "朱清瑜": "zqy",
  "王凯昕": "wkx",
  "尹杰": "yj",
  "薛磊": "xl",
  "童熙年": "txn",
};

export function getPinyinInitials(name: string): string {
  if (!name) return "";
  const trimmed = name.trim();
  if (STUDENT_PINYIN_MAP[trimmed]) {
    return STUDENT_PINYIN_MAP[trimmed];
  }
  return trimmed.toLowerCase();
}
